USE [master]
GO

/****** Object:  Database [Compromissos]    Script Date: 23/07/2021 20:14:25 ******/
CREATE DATABASE [Compromissos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Compromissos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Compromissos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Compromissos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Compromissos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Compromissos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Compromissos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Compromissos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Compromissos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Compromissos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Compromissos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Compromissos] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Compromissos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Compromissos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Compromissos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Compromissos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Compromissos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Compromissos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Compromissos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Compromissos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Compromissos] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Compromissos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Compromissos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Compromissos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Compromissos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Compromissos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Compromissos] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Compromissos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Compromissos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Compromissos] SET  MULTI_USER 
GO

ALTER DATABASE [Compromissos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Compromissos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Compromissos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Compromissos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Compromissos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Compromissos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Compromissos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Compromissos] SET  READ_WRITE 
GO

